[build]
  builder = "nixpacks"

[build.nixpacks]
  # Forzar PHP 8.3
  phpspec = "8.3"

[deploy]
  # Directorio donde está tu index.php o punto de entrada
  startCommand = "php -S 0.0.0.0:8000 -t api"
  healthcheckPath = "/api/restaurantes.php"
  numReplicas = 1
  restartPolicyType = "ON_FAILURE"